name: spin_wheel
version: 1.2.0

description: >
  A highly customizable, open-source spin wheel widget for Flutter. Perfect for games, promotions, lucky draws, and interactive apps. Supports custom layouts, animations, modular plugins, and vibrant backgrounds.
repository: https://github.com/zahir-patel/SpinWheenX
homepage: https://github.com/zahir-patel/SpinWheenX
issue_tracker: https://github.com/zahir-patel/SpinWheenX/issues
license: MIT
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  flutter_gif: ^0.0.4
  flutter_animate: ^4.2.0
  audioplayers: ^5.2.1
  confetti: ^0.7.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
