name: spin_wheel
version: 0.0.1
publish_to: none
description: A customizable Flutter-based Android Spin Wheel SDK.
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  flutter_gif: ^0.0.4
  flutter_animate: ^4.2.0
  audioplayers: ^5.2.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
